CXX_WARN_FLAGS_EIGEN=-Wall -Wfloat-equal -std=c++98
CXX_WARN_FLAGS=${CXX_WARN_FLAGS_EIGEN} -Wshadow -pedantic
IFLAGS+=-I../include
IFLAGS_EIGEN=${IFLAGS} -I/usr/local/include/eigen2/ -I/usr/include/eigen2/
LDFLAGS+=-L../lib/ -lsmpc_solver -lwmg

ifdef DEBUG
LDFLAGS+=-pg
CXXFLAGS=-g ${CXX_WARN_FLAGS} ${IFLAGS} -pg
CXXFLAGS_EIGEN=-g ${CXX_WARN_FLAGS_EIGEN} ${IFLAGS} -pg
CMAKEFLAGS=-DCMAKE_BUILD_TYPE=DEBUG
else
CXXFLAGS=-O3 -DNDEBUG ${CXX_WARN_FLAGS} ${IFLAGS}
CXXFLAGS_EIGEN=-O3 -DNDEBUG ${CXX_WARN_FLAGS_EIGEN} ${IFLAGS}
CMAKEFLAGS=-DCMAKE_BUILD_TYPE=Release
endif
